name: auth_repository
description: Dart package that manage Auth data for Tower Project
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.16.0
  flutter:
    sdk: flutter