name: messages_repository
description: Dart package that manage Messages data for Tower Project
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter